<?php

    const GENERAL_ERROR = ["msg"=>"Erro no servidor, por favor, entre em contato", "icon"=>"error"];
    const INVALID_PERMISSION = ["msg"=>"Você não tem permissão para tal ação!", "icon"=>"error"];
    const LOGGED = ["msg"=>"Login efetuado, redirecionando...", "icon"=>"success"];
    const USER_REGISTERED = ["msg"=>"Usuário cadastrado!", "icon"=>"success"];
    const WRONG_PASSWORD = ["msg"=>"Senha incorreta", "icon"=>"error"];
    const USER_UPDATED = ["msg"=>"Usuário atualizado com sucesso!", "icon"=>"success"];
    const USER_DELETED = ["msg"=>"Usuário deletado com sucesso!", "icon"=>"success"];
    const USER_NOT_FOUND = ["msg"=>"Usuário não cadastrado", "icon"=>"error"];
    const EMAIL_NOT_REGISTERED = ["msg"=>"Email não cadastrado", "icon"=>"error"];
    const EMAIL_ALREADY_EXISTS = ["msg"=>"Email já cadastrado!", "icon"=>"error"];
    const INVALID_EMAIL = ["msg"=>"Email inválido!", "icon"=>"error"];
    const EMPTY_FIELDS = ["msg"=>"Preencha o(s) campo(s) vazio(s)","icon"=>"error"];
    const ERRO_CONEXAO = ["msg"=>"Erro interno no servidor!","icon"=>"error"];
    const AREA_REGISTERED = ["msg"=>"Área cadastrada com sucesso","icon"=>"success"];
    const AREA_DELETED = ["msg"=>"Área deletada com sucesso","icon"=>"success"];
    const AREA_UPDATED = ["msg"=>"Área atualizada com sucesso","icon"=>"success"];
    const INVALID_ID_AREA = ["msg"=>"Área atualizada com sucesso","icon"=>"success"];
    const USER_FK_ERROR = ["msg"=>"Este usuário está relacionado à um ou mais projetos!","icon"=>"error"];
    const AREA_FK_ERROR = ["msg"=>"Este tipo de área está sendo usado em um ou mais projetos!","icon"=>"error"];
    const COURSE_FK_ERROR = ["msg"=>"Este curso está sendo usado em um ou mais projetos/usuários!","icon"=>"error"];
    const PROJECT_REGISTERED = ["msg"=>"Projeto cadastrado com sucesso","icon"=>"success"];
    const PROJECT_CREATED = ["msg"=>"Projeto Criado com êxito!","icon"=>"success"];
    const INVALID_DATE_TIME = ["msg"=>"Data e hora inválida.", "icon"=>"error"];
    const LARGER_SIZE = ["msg"=>"Tamanho do arquivo excede o limite!","icon"=>"error"];
    const CHANGE_PASSWORD_REQUEST_SEND = ["msg"=>"Foi enviado um link de recuperação de senha neste email!","icon"=>"success"];
    const PASSWORD_CHANGED = ["msg"=>"Senha alterada com sucesso!","icon"=>"success"];
    const LARGER_SERVER_SIZE = ["msg"=>"Tamanho do arquivo excede o limite do servidor!","icon"=>"error"];
    const MEDIA_DELETED = ["msg"=>"Mídia Deletada!","icon"=>"success"];
    const INVALID_TYPE_USER = ["msg"=>"Tipo de usuário inválido!","icon"=>"error"];
    const INVALID_TOKEN = ["msg"=>"Token inválido!","icon"=>"error"];
    const MEDIA_UPDATED = ["msg"=>"Mídia alterada com sucesso!","icon"=>"success"];
    const INVALID_COURSE = ["msg"=>"Curso inválido!","icon"=>"error"];
    const INVALID_ID = ["msg"=>"ID inválido, recarregue a página, e tente novamente!","icon"=>"error"];
    const PROJECT_UPDATED = ["msg"=>"Projeto atualizado com sucesso!","icon"=>"success"];
    const COURSE_REGISTERED = ["msg"=>"Curso cadastrado!","icon"=>"success"];
    const COURSE_UPDATED = ["msg"=>"Curso atualizado!","icon"=>"success"];
    const COURSE_DELETED = ["msg"=>"Curso deletado com sucesso!","icon"=>"success"];
    const PROJECT_DELETED = ["msg"=>"Projeto deletado com sucesso!","icon"=>"success"];
    const INVALID_AREA = ["msg"=>"Área do projeto inválido!","icon"=>"error"];
    const FILE_NOT_SEND = ["msg" => "Não há uma imagem anexada!", "icon" => "error"];
    const FILE_TOO_BIG = ["msg"=>"O tamanho da imagem excede 2.5MB!", "icon"=>"error"];
    const ERROR_UPLOAD = ["msg"=>"Erro ao enviar arquivo, tente novamente ou entre em contato!","icon"=>"error"];
    const NOTHING_FOUND = "<h2>Nenhum projeto criado!</h2>";